<a href="https://colab.research.google.com/github/hshanes/hw4503/blob/main/chw_3_Hannah_Shanes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/scaomath/wustl-math450/blob/main/Homework/chw-3_YOUR_NAME.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 3: Classification problems
Name: Hannah Shanes

Wustlkey: hshanes

Partner Name (if applicable):

Partner Wustlkey (if applicable):

### Submission instructions

- Submit the modified python notebook as homework submission.
- Group submission is enabled, you can submit this coding assignment with up to 1 teammate in our class. For instruction of how to do a group submission. Please refer to Canvas useful links.
- You can google answers on StackOverflow, please attach the corresponding StackOverflow answer as comments. However, if the answer is converted to `torch` format, no credit will be awarded.
- Do not change the number of cells! Please work in the cell provided. If we need extra cells for debugging and testing purposes, we can work at the end of this notebook, save everything as a backup for review, and delete the extra cells in the submitted version.

 

### Instructions
Do **not** use `for` loops for computational purpose in any of our solutions! We are allowed to use `for` loops to display figures etc.
Efficieny will be graded as well. For example if a problem asks us generate an array from 0 to 9: then
```python
x = []
for i in range(10):
    x.append(i)
```
this will only result a partial credit while
```python
x = np.arange(10)
```
or
```python
x = torch.arange(10)
```
will yield a full score.

### Problems
Below are 4 problems that explore the needed data structure and operations for classification problems. Complete the coding tasks for credit.

### Grading
This homework has 4 problems, 5 points for each problem. The homework will be graded and the grade counts towards your course grade. 

## Coding environments and submission
If we do not have `torch` installed on your computer, we have three ways to upload this notebook to [Google colab](https://colab.research.google.com/)：

1. Open up Google Colab, choose `Upload` to upload this template and work there. After we have done working we can select `File->Download .ipynb`.
2. Open up Google Colab, choose either `GitHub` or `Google Drive` to select the uploaded notebook in the corresponding website. After done working, we can sync the file to the corresponding GitHub or Google Drive copy.
3. Use the "Open in Colab" button at the top.

In [2]:
# Run Me First
import torch

# import torchvision 
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from torchvision.utils import make_grid

# import packages that help us plot
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("dark")

## Dataset


"MNIST ("Modified National Institute of Standards and Technology") is the de facto “hello world” dataset of computer vision. Since its release in 1999, this classic dataset of handwritten images has served as the basis for benchmarking classification algorithms. As new machine learning techniques emerge, MNIST remains a reliable resource for researchers and learners alike."

In the following cells, we will learn how to load and view this dataset for our toy models. 

Read more:[https://www.kaggle.com/c/digit-recognizer](https://www.kaggle.com/c/digit-recognizer)


<a title="By Josef Steppan [CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0)], from Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:MnistExamples.png"><img width="512" alt="MnistExamples" src="https://upload.wikimedia.org/wikipedia/commons/2/27/MnistExamples.png"/></a>


---- 
This code is adopted from the pytorch examples repository. 
It is licensed under BSD 3-Clause "New" or "Revised" License.
Source: https://github.com/pytorch/examples/
LICENSE: https://github.com/pytorch/examples/blob/master/LICENSE

In [3]:

## update as of Mar 11
!wget https://sites.wustl.edu/scao/files/2021/03/MNIST.tar_.gz
!mv MNIST.tar_.gz MNIST.tar.gz
!tar -zxvf MNIST.tar.gz

--2021-03-14 19:36:38--  https://sites.wustl.edu/scao/files/2021/03/MNIST.tar_.gz
Resolving sites.wustl.edu (sites.wustl.edu)... 34.215.37.29, 34.216.237.15
Connecting to sites.wustl.edu (sites.wustl.edu)|34.215.37.29|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cpb-us-w2.wpmucdn.com/sites.wustl.edu/dist/1/2774/files/2021/03/MNIST.tar_.gz [following]
--2021-03-14 19:36:39--  https://cpb-us-w2.wpmucdn.com/sites.wustl.edu/dist/1/2774/files/2021/03/MNIST.tar_.gz
Resolving cpb-us-w2.wpmucdn.com (cpb-us-w2.wpmucdn.com)... 151.139.244.23
Connecting to cpb-us-w2.wpmucdn.com (cpb-us-w2.wpmucdn.com)|151.139.244.23|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23197619 (22M) [application/gzip]
Saving to: ‘MNIST.tar_.gz’

MNIST.tar_.gz       100%[===================>]  22.12M  --.-KB/s    in 0.09s   

2021-03-14 19:36:39 (235 MB/s) - ‘MNIST.tar_.gz’ saved [23197619/23197619]

./MNIST/
./MNIST/processed/
./MNIST/raw/
./MNIST/raw

In [4]:
# download the data
train = datasets.MNIST(root='./', train=True, download=True, transform = transforms.ToTensor())

Using downloaded and verified file: ./MNIST/raw/train-images-idx3-ubyte.gz
Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw
Using downloaded and verified file: ./MNIST/raw/train-labels-idx1-ubyte.gz
Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw
Using downloaded and verified file: ./MNIST/raw/t10k-images-idx3-ubyte.gz
Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw
Using downloaded and verified file: ./MNIST/raw/t10k-labels-idx1-ubyte.gz
Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw
Processing...
Done!


/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:479: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [6]:
data_new = train.data[:10000].clone() # first 10000 samples
target_new = train.targets[:10000].clone()

## One-hot encoding of labels

Encode labels as a "one-hot" numeric array. In binary classification, essentially a vector representation of the following indicator function:
$$
1_{\{y = k\}} = \delta_{yk} = \begin{cases}
1 & \text{when } y = k,
\\[5pt]
0 & \text{otherwise}.
\end{cases}
$$

For example, if we have 4 classes `0, 1, 2, 3`, class `0` will be one-hot encoded as `[1, 0, 0, 0]`, and class `2` as `[0, 0, 1, 0]`.


## Problem 1
Write a function `one_hot_encode()` to convert the class labels of MNIST dataset to a matrix of one-hot encoded vectors,
each row represents the label of a sample. You can use `for` loop, but `for` loop will not be rewarded with full credits.
An example for `for` loop implementation is as follows
 
```python
n_sample = len(data_new)
n_class = 10
one_hot_encoded_labels = torch.zeros((n_sample, 10), dtype=torch.float)
for i in range(n_sample):
    k = target_new[i]
    one_hot_encoded_labels[i, k] = 1
```

There are various way of implementation the one-hot encoding without `for` loop, for example, expanding dimensions, using an identity matrix, etc. You can google StackOverflow to get answers, please attach the corresponding StackOverflow answer as comments if you have done so. However, if the answer has not been converted to `torch` format, no credit will be awarded. Only the usage of a `torch` function is allowed.

In [7]:
import numpy as np

def one_hot_encode(y):

    classes=10
    targets = np.array(y).reshape(-1)
    return np.eye(classes)[targets]



print(one_hot_encode(target_new[:10]))
# expected output
# tensor([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
#         [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
#         [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
#         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
#         [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
#         [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
#         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
#         [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
#         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
#         [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


## Softmax function

Softmax function is a tool for multi-class classification problem. Suppose that we know for a certain sample, its label $y\in \{1,\dots, K\}$ where $K$ is the number of all possible classes in the samples. For a sample image flattened $\mathbf{x}\in \mathbb{R}^n$ (in MNIST it is a 28x28 image flattened to a `(784,)` array), we can estimate the probability that $P(y=k|\mathbf{x})$ using our neural network's output as follows:

$$
\begin{pmatrix}
P(y = 1 | \mathbf{x}; W) \\
P(y = 2 | \mathbf{x}; W) \\
\vdots \\
P(y = K | \mathbf{x}; W)
\end{pmatrix}
=\text{Softmax} (\hat{y}_1, \hat{y}_2, \dots, \hat{y}_K)
:= \frac{1}{ \sum_{j=1}^{K}{\exp\big(\hat{y}_j\big) }}
\begin{pmatrix}
\exp(\hat{y}_1) \\
\exp(\hat{y}_2) \\
\vdots \\
\exp(\hat{y}_K) \\
\end{pmatrix}.
$$
where we have $K$ outputs from a neutral network (preferably after a ReLU activation in the last layer), $\hat{y}_1, \hat{y}_2, \dots, \hat{y}_K$ are outputs,  and the factor $\sum_{j=1}^{K}{\exp\big(\hat{y}_j\big)}$ normalizes the results to be a probability (each entry is between 0 to 1, and summing up to 1).

## Problem 2

Implement a vectorized `softmax()` function by ourselves without referring to `torch.nn.functional.softmax()`, i.e., for a `(N, 10)` matrix which contains the outputs of neural network, the function should return the same matrix with the `proba` produced in the following `for` loop:

```python
N = len(data_new)
y_hat = torch.randn((N, 10)) # generate a random guess
proba = torch.zeros_like(y_hat)
for i in range(N):
    exp_y_hat = torch.exp(y_hat[i])
    sum_exp = torch.sum(exp_y_hat)
    proba[i] = exp_y_hat/sum_exp

```

In [8]:
def softmax(y):
    '''
    Replace this with your code
    
    Input:
        - yhat: (N, K) matrix
            N: number of samples
            K: number of classes
    Output:
        - proba: (N, K) matrix
    '''
    y=torch.exp(y)
    denom=y.sum(dim=1)
    denom=denom.view(-1,1)
    proba=y/denom
    return proba


N = len(data_new)
y_hat = torch.randn((N, 10))
proba = softmax(y_hat)
print(torch.allclose(proba.sum(axis=1), torch.ones(N))) # expected output is True

True


## Generating the prediction 

After we get the probability, to predict which class this sample belongs to, we simply choose the biggest entry as the class.
For example, if we have a 4-class classification problem, the predicted probability for a sample can be 
- `[0.3, 0.1, 0.4, 0.2]`,  the `pred` for this sample is of class `2`.
- `[0.05, 0.8, 0.05, 0.1]`,  the `pred` for this sample is of class `1`.
- `[0.6, 0.1, 0.2, 0.1]`,  the `pred` for this sample is of class `0`.

## Metrics for classification problem

- Accuracy: the simplest metric in classification, if the label(s) predicted for a sample match the true label(s) associated with this sample, we say this is a correct prediction, otherwise incorrect. The accuracy metric is simply:
$$
\text{Acc} = \frac{1}{N}\sum_{i=1}^{N}\frac{|y^{(i)}\cap \hat{y}(x^{(i)}; W)|}{| \hat{y}(x^{(i)}; W)|} = \frac{\# \text{Correct}}{\# \text{Total}}
$$

## Problem 3

Write a vectorized function `proba_to_pred()` that converts the predicted probability matrix in problem 2 to prediction vector, i.e., for each row of the probability matrix, find where its maximum entry is (the index of the maximum entry in that row).

## Problem 4
Write a vectorized function `accuracy_score()` function to compute the accuracy between predicted labels and the true labels. 
A `for` loop implementation can be follows: suppose `pred` is the predicted class vector that has same shape with `target_new` we defined earlier.

```python
N = len(target_new)
counter = 0
for i in range(N):
    counter += (target_new[i] == pred[i])

acc = counter/N
```


In [16]:
def proba_to_pred(proba):
    '''
    Replace this with your code
    
    Input:
        - predicted probability matrix: (N, K)
            N: # samples
            K: # of classes
        
    Output:
        - pred: predicted classes (N, )
    '''
    pred = torch.argmax(proba, dim=1)

    return pred

def accuracy_score(y1, y2):
    '''
    Replace this with your code
    
    Input:
        - predicted labels: one-hot encoded prediction
        - true labels: one-hot encoded true labels

    Output:
        - accuracy score above
    '''
    acc=(y1==y2).float().mean()
    
    return acc


y_hat = torch.randn((target_new.size(0), 10)).softmax(dim=1) # random guess then softmax
pred = proba_to_pred(y_hat) # your implemented function in problem 3
acc = accuracy_score(pred, target_new) 

print(pred.min(), pred.max()) # expected output: 0 9
print(acc) # expected output approximately 0.1 (random guess's correct rate)

tensor(0) tensor(9)
tensor(0.1037)


In [17]:
# extra cells
